### ISSUE TITLE
[Issue] So, this won't prevent shotgun thrown on the floor from going off the fire on purpose

### ISSUE THREAD

**Issue by CoolLKKPS** [AgentRev/LC-NoFriendlyGunfire#1]
same as topic

**Comment by CoolLKKPS** [comment]
@AgentRev fix that pls

**Comment by AgentRev** [comment]
NoFriendlyGunfire only disables damage while the gun is being held by player. It is possible to disable shotgun misfires but it is not the intent of this mod. I can however make a separate mod if you want.

**Comment by CoolLKKPS** [comment]
is there no other way to prevent that when as client? uh.... i really hate kids playin LC now

**Comment by AgentRev** [comment]
To join a game? What are you talking about?

**Comment by CoolLKKPS** [comment]
i mean join a lobby

**Comment by CoolLKKPS** [comment]
sry im not speak English too much, there may be grammatical issues in some places

**Comment by AgentRev** [comment]
Wait, actually, I could change the mod so it disables damage when the gun is not held by an enemy instead of checking if the gun held by a player, this would block damage from shotguns falling on the floor

**Comment by CoolLKKPS** [comment]
really? yea do it, i don't want to experience again now, specially when cheater know shovel can't deal dmg to me, they will use shotgun instead
quote this issue: https://github.com/7PH/reverse-grief-lethal-company-mod/issues/1

**Comment by AgentRev** [comment]
Just pushed update v1.0.2, should fix the problem

**Comment by CoolLKKPS** [comment]
nice!
